version: '3'

services:
  postgres:
    image: postgres
  rabbit:
    image: "rabbitmq:latest"
    ports:
      - "5672:5672"
  web:
    build: .
    command: ["gunicorn", "bruceguts.http:app", "-k", "gevent", "-b", "0.0.0.0:80"]
    ports:
      - "8080:80"
    depends_on:  &services
      - postgres
      - rabbit
    environment: &env
      - CELERY_BROKER=amqp://rabbit
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432
    volumes: &code
      - .:/app
  worker:
    build: .
    volumes: *code
    command: ["celery", "-A", "bruceguts.tasks", "worker", "--loglevel=info"]
    environment: *env
    depends_on: *services
  flower:
    build: .
    volumes: *code
    command: ["celery", "flower", "-A", "bruceguts.tasks", "worker", "--loglevel=info", "--address=0.0.0.0", "--port=5555"]
    ports:
      - "5555:5555"
    environment: *env
    depends_on: *services
